Repository regen-network/regen-ledger, pull requests merged in 2021-09, with the labels that each got.

#488 style(orm): improve documentation and extract common code
  orm/table.go
Labels: Scope: ORM

#504 chore: go.mod: bump IBC version
  go.mod
  go.sum
Labels: dependencies

#514 fix: use ctx.Codec when marshaling for generated batch json in CLI
  x/ecocredit/client/testsuite/tx.go
  x/ecocredit/client/tx.go
  x/ecocredit/location.go
Labels: Scope: x/ecocredit

#522 docs: fix ecocredit proto comments
  client/docs/swagger-ui/swagger.yaml
  proto/regen/ecocredit/v1alpha1/tx.proto
  proto/regen/ecocredit/v1alpha1/types.proto
  x/ecocredit/spec/protobuf.md
  x/ecocredit/tx.pb.go
  x/ecocredit/types.pb.go
Labels: v2.0.0 Release Audit

#559 feat: add simulations for update credit class messages
  x/ecocredit/simulation/operations.go
Labels: Status: Nice To Have
